### PR TITLE
Purescript 0.15

### LINKED ISSUE #50: bump to purescript-0.15
purescript-0.15 was released a few days ago.  It would be nice if `purenix` was compatible with it.  I'm not sure how much work would need to go into this:

https://github.com/purescript/purescript/releases/tag/v0.15.2

### PR DESCRIPTION
**Pull request by jonascarpay**
Closes #50

### CODE REVIEW

**Comment by jonascarpay** [comment]
Do we want to support both 0.14 and 0.15? This is tricky, because 0.15 no longer uses a separate `purescript-cst` package. We'd have to find a way to make the dependency optional, or ship a useless and outdated extra package.

This branch is not backwards compatible, but I also pushed [a different branch that is](https://github.com/purenix-org/purenix/compare/purescript-0.15...purescript-0.15-backwards-compatible?expand=1).

What do you think, @cdepillabout ?

**Comment by cdepillabout** [comment]
I'm completely fine with just supporting purescript-0.15.

I'm pretty sure the other purescript backends only support a single version of purescript, so it makes sense for us to do the same.

Although someone that actually wanted to use purenix plus the package set would have to go through and update all our `purescript-*` packages under https://github.com/orgs/purenix-org/repositories to the corresponding upstream version for purescript-0.15.

**Comment by cdepillabout** [comment]
I'm going to unsubscribe while you're working on this, but feel free to ping me or request a review if you have something you want me to look at or a question or something.

**Review by cdepillabout — APPROVED** [review]
This LGTM, thanks for fixing this up!

**Pull request merged**
