### PR TITLE
Escaping fix + test suite

### LINKED ISSUE #5: test suite
It would be nice to have a test-suite for `purenix`.

The most important tests would be for the `Nix.Convert` and `Nix.Print` modules.

We'd also especially like to test that all our identifiers and attrset keys get escaped correctly.

Places to pull ideas from:
- PureScript test suite: https://github.com/purescript/purescript/tree/master/tests
- purescm test suite: https://github.com/purescm/purescm/tree/master/test

As of this writing, neither [purerl](https://github.com/purerl/purerl) nor [purescript-native](https://github.com/andyarvanitis/purescript-native) have a test suite.

### LINKED ISSUE #35: characters in quotes aren't escaped correctly
It looks like some characters in quotes aren't escaped correctly.

I haven't extensively tested this, but here is one example I've found:

```purescript
module Main where

example :: String
example = "\""
```

This compiles to:

```nix
let
  module = { };
  example = """;
in
  {inherit example;}
```

But `example` should probably be `"\""`.

### PR DESCRIPTION
**Pull request by jonascarpay**
Fixes #35
Fixes #5

This PR contains a rudimentary test suite, as well as a fix for the escaping issue.

- [x] More tests for string edge cases
- [x] ~Don't actually just `show` in Haskell~ the more I think about it the more I think this is fine
- [x] Run on CI
- [x] Better type for `run`

### CODE REVIEW

**Comment by jonascarpay** [comment]
I'm on mobile, which doesn't show when or how this got marked as ready for review, and I can't change it back. But just to be sure, it's not ready yet, I'll request review when it is.

**Comment by cdepillabout** [comment]
@jonascarpay No problem, I switched it back to draft for you.

**Comment by jonascarpay** [comment]
After some offline discussion, we decided that the test suite needs a better design before being worth merging.

The issue with a test suite like this is that the most interesting thing about them is not that they pass, but that they run at all, because that already means that we are compiling and executing _something_. So, we either need a test suite that (somehow) provides more obvious additional benefit, or fully leans into the fact that it's more of a integration test than a unit test, or in some other ways better isolates the guarantees we want it to provide.

**Comment by thought2** [comment]
hi @jonascarpay 
cool, that you are adressing those issues! Today I got aware of a thing, that may be helpful:
On main the commit 72cc3ffdea361322c169fdbe1c9572117dcda075 introduces a bug that causes escape sequences like `\x001b[32m` to be printed as `ESC[32m` when logged/traced to the commandline. It should actually turn the following text's color to be green instead.
I tried it with the f29c0149c4d473d9326208ce293239ac354b206b from your PR branch and it's the same behavior.
I cannot investigate details right now, If it's not related I can open up a separated issue.

**Comment by jonascarpay** [comment]
@thought2 Oh wow, that's a very good catch! Please open a separate issue, and I'll have a think how to best go about fixing it. I guess that with our strings passing through Nix, PureScript, Haskell (and arguably Bash) just using `show`, and that handling all our escaping concerns was too good to be true :smiling_face_with_tear: .

**Pull request closed without merging**
